sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - 0.12
  - 4
  - 6
  - 7

before_install:
  - mkdir node_modules; ln -s ../ node_modules/event-emitter

notifications:
  email:
    - medikoo+event-emitter@medikoo.com

script: "npm test && npm run lint"
